# Generated by Django 4.1.5 on 2023-01-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('horas', models.IntegerField(max_length=5)),
                ('creditos', models.IntegerField(max_length=5)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(max_length=6)),
            ],
        ),
    ]
